### PR TITLE
Use VSbuild task in CI

### PR DESCRIPTION
**Pull request by networkfusion**
## Description
* Switch from MSBuild task to VSbuild task.
* Ensures the solution build correctly in all CI contexts.

## Motivation and Context
* CI in other projects were failing.
* Fixes the related package lock issue.
* Further improves tests in CI.

## How Has This Been Tested?
* CI Build completes

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by josesimoes** [comment]
Don't understand the need to change this... If this is working, why change it?

**Comment by networkfusion** [comment]
> Don't understand the need to change this... If this is working, why change it?

It is not in all circumstances.
For instance, https://github.com/nanoframework/nanoframework.github.io/ uses VSBuild rather than MSBuild tasks. It works fine on VS2017, but updating the VM image to VS2022 it starts failing.

Rather than a "work around" (https://github.com/nanoframework/nanoframework.github.io/pull/139), I thought it is better to "fix" the actual issue...

And... it comes back to package lock...

**Comment by networkfusion** [comment]
Also... In Azure pipelines, the MSBuild task seems to be more lenient when it comes to package lock. VSBuild (for better or worse) seems to expose issues easier... That and I am guessing the nf-tools repo is also using it for downstream checks.

**Comment by networkfusion** [comment]
And as proof, see https://dev.azure.com/nanoframework/CoreLibrary/_build/results?buildId=39195&view=logs&j=9c317a41-c6cf-53ec-384d-ce4077395c24&t=4332255a-e948-527c-938b-0b3167ddd05f vs https://dev.azure.com/nanoframework/CoreLibrary/_build/results?buildId=39196&view=results

**Comment by josesimoes** [comment]
@networkfusion all our class libraries as using VSBuild. 
These tasks that you see here on mscorlib using msbuild are the second calls after the unit tests are run in order to get the assembly native checksums, which can not be grabbed on the 1st pass (as it happens with all the other libs) because of unit test running and the fact that this is doing a "double" build: the reflection and the no-reflection flavour.

The random fails that you're seeing on the pipelines are due to the fact that sometimes (I can't understand why) nuget it's restoring it from the Azure feed instead of nuget.org and that causes a mismatch.
Sometime ago I've added the retry option to the restore task hopping that it would take care of this. Unfortunately it doesn't as it keeps using the local cache (which has been loaded with the "wrong" version on the 1st pass).
Therefore the fix for this it's elsewhere not switching from VSBuild to msbuild task.

**Comment by networkfusion** [comment]
Closing this one due to guidance above.

**Pull request closed without merging**
