### PR TITLE
Adding some unit tests for `string`

### PR DESCRIPTION
**Pull request by CoryCharlton**
## Description
- Added unit tests to cover changes in https://github.com/nanoframework/nf-interpreter/pull/2826

## Motivation and Context
- There was no unit test coverage

## How Has This Been Tested?
- Unit tests ;-)

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [X] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [X] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [X] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [X] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [X] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by CoryCharlton** [comment]
@josesimoes The issue was that none of the tests run in my environment due to the following error:

`Could not find test executor with URI 'executor://nanoframeworktestexecutor/'.  Make sure that the test executor is installed and supports .net runtime version  .`

I'm assuming this is related to my environment though and I ran these tests in my other repository against a custom firmware build so I'll toss this over.

**Review by josesimoes — COMMENTED** [review]
There are already a bunch of tests for `string`, no point on scattering them.
Better have these new ones along with those, OK? Sorry for the extra work...

**Comment by CoryCharlton** [comment]
> There are already a bunch of tests for `string`, no point on scattering them. Better have these new ones along with those, OK? Sorry for the extra work...

No worries, I didn't look hard enough (or at all beyond the fact that there was no project with "String" in the name 😛). I moved them.

**Review by josesimoes — APPROVED** [review]
Perfect! Thanks. 👍🏻 +1

**Pull request merged**
