### PR TITLE
Fix access beyond array boundaries in SpanByte

### PR DESCRIPTION
**Pull request by gukoff**
## Description

Fix array access similarly to how it's done in https://github.com/nanoframework/nanoFramework.IoT.Device/pull/29

## Motivation and Context
- Fixes a bug

## How Has This Been Tested?

Not tested.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by gukoff** [comment]
I think there are no tests for SpanByte in the repo. Should we add them in this PR too?

**Comment by josesimoes** [comment]
Yes please! Let's have unit tests for this.

**Review by Ellerbach — APPROVED** [review]
Thanks for the submission. And spotting the potential issue

**Comment by gukoff** [comment]
My VS doesn't recognize the tests here, I think because there are [special guidelines](https://github.com/nanoframework/CoreLibrary#unit-test). I'll see if following them fixes the issue, and then look into tests.

**Pull request merged**
