### PR TITLE
Adds negative test of Enum.HasFlag

### PR DESCRIPTION
**Pull request by SandorDobos**
## Description
Supports nanoFramework/Home#730

## Motivation and Context

- Resolves nanoFramework/Home#730

## How Has This Been Tested?

Executed the test method :)

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [x] Unit Tests (work on Unit Tests, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by josesimoes — CHANGES_REQUESTED** [review]
Could you please reuse the existing enum flags and adapt the test methods.
I've recently removed the repeated enum flags that where there.
There is no point on adding new enums just because... If the one there is suitable for the test lets use it. DRY and KISS, please. 😉

**Comment by SandorDobos** [comment]
I need two enums because this test requires two separate enum types.
I could reuse the existing enum instead of one of them but that will make the test less readable because the second enum still has to be defined somewhere. Should I do this even so?

**Comment by josesimoes** [comment]
> I need two enums because this test requires two separate enum types.
> I could reuse the existing enum instead of one of them but that will make the test less readable because the second enum still has to be defined somewhere. Should I do this even so?

I've missed your point on using 2 enums. Now I can see that.
Then please "duplicate" the existing enum and do exactly what you're doing. This was that second enum will be available for news tests than need some something similar.
Does this make sense to you?

**Comment by SandorDobos** [comment]
Done

**Review by josesimoes — APPROVED** [review]
Perfect! Thanks.

**Pull request merged**
