### PR TITLE
Add AggressiveInlining and other missing options

### PR DESCRIPTION
**Pull request by CoryCharlton**
## Description
- Add AggressiveInlining and other missing options.

## Motivation and Context
These options were added since the original commit of these classes.

## How Has This Been Tested?
Locally. All code was copied from the .NET Core 8.0 source.

## Types of changes

- [X] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [X] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [X] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [X] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [X] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by josesimoes** [comment]
@CoryCharlton have you tested these attributes in a test application?
I have a vague recollection of testing these and some didn't produce any change in the IL generated and even think one of them produced code that our execution engine couldn't run...

Another question: why have you changed the license header?

**Comment by CoryCharlton** [comment]
> @CoryCharlton have you tested these attributes in a test application? I have a vague recollection of testing these and some didn't produce any change in the IL generated and even think one of them produced code that our execution engine couldn't run...
> 
> Another question: why have you changed the license header?

@josesimoes I was copy/pasting the code from the .NET 8.0 source so that's why the license changed. Happy to update it back to what it originally was if that's the right thing to do.

I was able to observe signature differences in the IL generated using the different flags. My understanding it that the actual inlining occurs during JIT so I have not been able to confirm that and am not sure if it will work in NF.

I did run a simple test app but being that this is the core library I was not able to run any benchmarks. I'll add some simple unit tests that can be run on device.

**Comment by josesimoes** [comment]
> > Another question: why have you changed the license header?
> 
> @josesimoes I was copy/pasting the code from the .NET 8.0 source so that's why the license changed. Happy to update it back to what it originally was if that's the right thing to do.

Yes please to keep the headers consistent throughout the code base. 

> I was able to observe signature differences in the IL generated using the different flags. My understanding it that the actual inlining occurs during JIT so I have not been able to confirm that and am not sure if it will work in NF.

Now that you mention it, it's coming to my mind. Those with related with JIT don't make sense, as our EE doesn't support that.

> I did run a simple test app but being that this is the core library I was not able to run any benchmarks. I'll add some simple unit tests that can be run on device.

All in all, I don't think any of these will have any effect...

**Comment by CoryCharlton** [comment]
> All in all, I don't think any of these will have any effect...

With that in mind do you suggest we ditch these changes or include them for consistency (ex: when we're pulling in code from .NET Full) and potential future use?

**Comment by josesimoes** [comment]
@CoryCharlton to be honest, I would leave them out. If they will be of use in the future, we can go and grab them. Adding them "just in case" will only have the effect of increasing flash space and forcing a new release of mscorlib for nothing... 

Sorry about the time you spent on this. Always preferable to start a conversation before adding new stuff. Unless you're having fun with something or rambling about a new idea, of course! (creativity should always be encouraged 😉 )

**Pull request closed without merging**
