### PR TITLE
Rework Unit Tests and Test Framework

### PR DESCRIPTION
**Pull request by CoryCharlton**
## Description
- Update TestFramework submodule
- Switching Output.WriteLine to comments to reduce string count

## Motivation and Context
Improved unit test output

## How Has This Been Tested?
Manually

## Types of changes

- [X] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [X] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [X] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [X] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [X] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [X] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by CoryCharlton** [comment]
** DO NOT MERGE **

I'm still waiting for https://github.com/nanoframework/nanoFramework.TestFramework/pull/259 to be merged. At that point I will update the submodule and fix the "incepted" libraries to include all the new files.

**Comment by josesimoes** [comment]
@CoryCharlton PR with test framework [v2.1.107](https://github.com/nanoframework/nanoFramework.TestFramework/releases/tag/v2.1.107) is out!

**Comment by CoryCharlton** [comment]
@josesimoes I updated the `nanoFramework.TestFramework` submodule and confirmed all the tests run. 

This PR is ready to be merged.

**Review by josesimoes — APPROVED** [review]
Brilliant! 
Lots of tests => lots of work!! 
Thanks for taking care of this.
I've reverted some of those on which there was a clear intention of outputting something.

**Pull request merged**
